---
# No hosts or gather_facts here as it's defined in the master playbook
- name: Download Kafka tarball from the official site
  get_url:
    url: "https://downloads.apache.org/kafka/3.8.0/kafka_2.13-3.8.0.tgz"
    dest: "/tmp/kafka_2.13-3.8.0.tgz"
    mode: '0755'
  register: download_result

- name: Check download result
  debug:
    var: download_result