---
# playbook_retrieve_facts_vms.yaml

- name: "Retrieve facts for created VMs"
  openstack.cloud.server_info:
    cloud: "{{ cloud }}"
    name: "{{ vm_name_prefix }}-{{ item }}"
  loop: "{{ range(1, 5) | list }}"
  register: vm_info

- name: "Update inventory file with VM IPs"
  lineinfile:
    path: ./inventory
    insertafter: "# Replace the lines below with actual IP addresses of the VMs after they are created"
    line: "{{ item.servers[0].addresses[network_name][0]['addr'] }} ansible_user={{ cloud_user }}"
  loop: "{{ vm_info.results }}"
  when: item.servers[0].status == "ACTIVE"