---
# playbook_install_pip_packages.yaml

- name: "Install required pip packages"
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - docker-compose
    - openstacksdk
    - ansible
  vars:
    ansible_python_interpreter: /usr/bin/python3
